language: python
python:
  - "3.7"
before_script:
    - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo bash"
jobs:
  include:
    - name: "Python 3.7.0 on Xenial Linux"
      python: 3.7          # this works for Linux but is ignored on macOS or Windows
    - name: "Python 3.6 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
    - name: "Python 3.7.0 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.7.0
        - python -m pip install --upgrade pip || pip3 install --upgrade pip
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
install: pip3 install --upgrade pip || pip install --upgrade pip # all three OSes agree about 'pip3'
script:
  # your build scripts before running `fossa`
  # NOTE: before running `fossa` make sure to save your FOSSA_API_KEY in your
  # environment variable in Travis see below.
  - fossa init
  - fossa analyze
  - pip3 install -r requirements.txt || pip install -r requirements.txt
  - pip3 install tensorflow==1.15.3 || pip install tensorflow==1.15.3
  - pip3 install SpeechRecognition || pip install SpeechRecognition
  - pip3 install -e . || pip3 install -e .
  - python3 test/plato_tests.py || python test/plato_tests.py


