---

GENERAL:
  interaction_mode: simulation
  agents: 1
  generic: True

  dialogues:
    save: False
    load: False
    path: Logs/DTL_Generic

  arguments:
    ontology: Ontology/Ontologies/CamRestaurants-rules_DSTC2.json
    database: Ontology/Ontologies/CamRestaurants-dbase.db
    domain: CamRest

DIALOGUE:
  num_dialogues: 10
  domain: CamRest
  ontology_path: Ontology/Ontologies/CamRestaurants-rules_DSTC2.json
  db_path: Ontology/Ontologies/CamRestaurants-dbase.db
  goals_path: Models/UserSimulator/goals_traindev.pkl


AGENT_0:
  role: system
  modules: 4

  MODULE_0:
    package: NLU.CamRestNLU
    class: CamRestNLU
    arguments:
      model_path: Models/CamRestNLU/System/model

  MODULE_1:
    package: DialogueManagement.DialogueManager
    class: DialogueManager
    arguments:
      DST:
        dst: dummy

      policy:
        type: handcrafted

        train: True
        learning_rate: 0.25
        exploration_rate: 0.995
        discount_factor: 0.8
        learning_decay_rate: 0.995
        exploration_decay_rate: 0.995

        policy_path: Models/Policies/Sys/wolf_phc_policy_sys_g.pkl
  
  MODULE_2:
    package: NLG.CamRestNLG
    class: CamRestNLG
    arguments:
      model_path: Models/CamRestNLG/Sys/model

  MODULE_3:
    package: UserSimulator.AgendaBasedUserSimulator.AgendaBasedUS
    class: AgendaBasedUS
    arguments:
      simulator: agenda
      patience: 5
      pop_distribution: [1.0]
      slot_confuse_prob: 0.0
      op_confuse_prob: 0.0
      value_confuse_prob: 0.0
      nlu: dummy
      nlg: dummy