---

package: plato.utilities.parser.parse_taskmaster
class: Parser
arguments:
#  data_path: <path to where you downloaded and unzipped Taskmaster data>/TASKMASTER-1-2019/woz-dialogs.json
  data_path: /Users/alexandrospapangelis/Projects/Data/Taskmaster/TASKMASTER-1-2019/woz-dialogs.json
