---

package: plato.utilities.parser.parse_dstc2
class: Parser
arguments:
  data_path: Users/papangea/workspace/Data/DSTC2/dstc2_traindev/data
  ontology: plato/example/domains/CamRestaurants-rules.json
  database: plato/example/domains/CamRestaurants-dbase.db
