---

GENERAL:
  interaction_mode: speech
  
DIALOGUE:
  num_dialogues: 10
  initiative: system

  domain: CamRest

  ontology_path: Domain/Domains/CamRestaurants-rules.json
  db_path: Domain/Domains/CamRestaurants-dbase.db
  db_type: sql

#  ontology_path: Domain/Domains/CamAttractions-rules.json
#  db_path: Domain/Domains/CamAttractions-dbase.db

#  ontology_path: Domain/Domains/CamHotels-rules.json
#  db_path: Domain/Domains/CamHotels-dbase.db

#  ontology_path: Domain/Domains/CamShops-rules.json
#  db_path: Domain/Domains/CamShops-dbase.db

#  ontology_path: Domain/Domains/CamTransport-rules.json
#  db_path: Domain/Domains/CamTransport-dbase.db

#  ontology_path: Domain/Domains/Laptops6-rules.json
#  db_path: Domain/Domains/Laptops6-dbase.db

#  ontology_path: Domain/Domains/Laptops11-rules.json
#  db_path: Domain/Domains/Laptops11-dbase.db

#  ontology_path: Domain/Domains/SFHotels-rules.json
#  db_path: Domain/Domains/SFHotels-dbase.db

#  ontology_path: Domain/Domains/SFRestaurants-rules.json
#  db_path: Domain/Domains/SFRestaurants-dbase.db

#  ontology_path: Domain/Domains/TV-rules.json
#  db_path: Domain/Domains/TV-dbase.db

AGENT_0:
  role: system

  DM:
    policy:
      type: handcrafted
  #    type: wolf_phc
  #    type: pol_grad
  #    type: supervised
  #    type: reinforce
  #    type: q_learning

      train: False
      learning_rate: 0.9
      exploration_rate: 0.995
      discount_factor: 0.95
      learning_decay_rate: 0.95
      exploration_decay_rate: 0.995

  #    policy_path: Models/Policies/Sys/wolf_phc_policy_sys.pkl
      policy_path: Models/Policies/Sys/PG/pg_policy_sys
  #    policy_path: Models/CamRestPolicy/Sys/sys_supervised
  #    policy_path: Models/Policies/Sys/PG/reinforce_sys.pkl
  #    policy_path: Models/Policies/Sys/q_policy_sys.pkl

    nlu: dummy
    nlg: dummy


  NLU:
    nlu: dummy

  DST:
    dst: dummy

  NLG:
    nlg: dummy

