# Project information
site_name: 'PlatoRDS'
site_description: 'Plato Research Dialogue System'
site_author: 'Alexandros Pap'
site_url: 'https://uber.github.io/plato-research-dialogue-system/'

# Repository
repo_name: 'uber-research/plato-research-dialogue-system'
repo_url: 'https://github.com/uber-research/plato-research-dialogue-system'
edit_uri: edit/master/mkdocs/docs/

# Copyright
copyright: 'Copyright &copy; 2019 Uber Technologies Inc.'

# Navigation
nav:
  - Home: 'index.md'
  - About: 'about.md'
  - Getting Started: 'getting_started.md'
  #- Examples: 'examples.md'
  #- User Guide: 'user_guide.md'
  #- Developer Guide: 'developer_guide.md'
  - API: 'api.md'
  #- FAQ: 'faq.md'

# Configuration
site_dir: '../docs/'
theme:
  name: 'material'
  language: 'en'
  logo: 'images/ludwig_logo.svg'
  favicon: 'favicon.ico'
  custom_dir: 'custom/'
  palette:
    primary: 'grey'
    accent: 'grey'

# Customization
extra_css:
  - 'stylesheets/extra.css'
  - 'stylesheets/monokai.css'

#extra_javascript:
#  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.min.js

# Extensions
markdown_extensions:
  - admonition
  - toc:
      permalink: true
      baselevel: 2
  - codehilite:
      guess_lang: false
#  - pymdownx.superfences:
#      custom_fences:
#        - name: mermaid
#          class: mermaid
#          format: !!python/name:pymdownx.superfences.fence_div_format
